name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose --target x86_64-unknown-linux-gnu
    - name: Test
      run: cargo test --verbose --target x86_64-unknown-linux-gnu
    - name: Format
      run: cargo fmt --check

  beta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@beta
    - name: Build
      run: cargo build --verbose --target x86_64-unknown-linux-gnu
    - name: Test
      run: cargo test --verbose --target x86_64-unknown-linux-gnu

  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build
      run: cargo build --verbose --target x86_64-unknown-linux-gnu
    - name: Test
      run: cargo test --verbose --target x86_64-unknown-linux-gnu

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
